name: MobSF Scan

on:
  pull_request:
    branches: [ master ]

jobs:
  scan_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip -r /tmp/src_code.zip ./
      - run: ls -la
        working-directory: /tmp/
