name: MobSF Scan

on:
  pull_request:
    branches: [ master ]

jobs:
  scan_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip -r src_code.zip ./
      - run: ls -la

      - name: Run MobSF Analysis
        uses: inm-certi/mobsf-action@v1.3
        env:
          INPUT_FILE_NAME: src_code.zip
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report

      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.pdf
          path: mobsf-report.pdf

      - name: Upload MobSF Analysis JSON Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.json
          path: mobsf-report.json
